[package]
name = "kdl-test"
version = "0.1.3"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
colored = "3"
rust-embed = "8.11.0"
serde_json = "1.0.149"
which = "6.0"

[workspace]
members = ["kdl-rs-decoder"]
